/**
 * Warning badge shown next to AI transcriptions.
 * Whisper does not support Memoni — its output is an educated guess based on
 * phonetic similarity to Urdu (the closest recognized language we send).
 * Admin must always listen to audio and correct the transcription before verifying.
 */
export function TranscriptionBadge() {
  return (
    <span
      className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-semibold text-white"
      style={{ backgroundColor: 'var(--color-warning)' }}
      title="This transcription was generated by AI (Whisper). Memoni is not a recognized language so the output may be inaccurate. Always listen to the audio and correct before verifying."
    >
      ⚠️ AI guess — verify before using
    </span>
  );
}
